[package]
name = "void_scrubbers_api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
