name: Build Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"
  # Allows manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Lint
        working-directory: ./backend
        run: cargo clippy -- -D warnings

      - name: Build
        working-directory: ./backend
        run: cargo build --release

      - name: Run tests
        working-directory: ./backend
        run: cargo test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend/target/release/void-scrubbers-backend
          retention-days: 90
